# Generated by Django 5.1.6 on 2025-03-25 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pertemuan', models.DateTimeField()),
                ('tujuan_pertemuan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_Reservasi', to=settings.AUTH_USER_MODEL)),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamu_Reservasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('Menerima_reservasi', 'Menerima Reservasi'), ('scan_qrcode', 'Scan QR codes')],
            },
        ),
        migrations.CreateModel(
            name='QRCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('tanggal_kadaluarsa', models.DateField()),
                ('reservasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='reservasi.reservasi')),
            ],
        ),
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('status_baru', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_changes', to=settings.AUTH_USER_MODEL)),
                ('reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservasi.reservasi')),
            ],
        ),
    ]
