# Generated by Django 5.1.6 on 2025-03-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadwal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pertemuan', models.DateTimeField(blank=True, null=True)),
                ('tujuan_pertemuan', models.TextField()),
                ('kode_unik', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checkin', 'Check-in'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservasi', to='jadwal.jadwal')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_reservasi', to=settings.AUTH_USER_MODEL)),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamu_reservasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_checkin', 'Can check-in reservations')],
            },
        ),
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checkin', 'Check-in'), ('completed', 'Completed')], max_length=20)),
                ('status_baru', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checkin', 'Check-in'), ('completed', 'Completed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_changes', to=settings.AUTH_USER_MODEL)),
                ('reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservasi.reservasi')),
            ],
        ),
    ]
