# Generated by Django 5.1.6 on 2025-03-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='kode_unik',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
