# Generated by Django 5.1.6 on 2025-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestverifications',
            name='ktp_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestverifications',
            name='selfie_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
