# Generated by Django 5.1.6 on 2025-03-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestverifications',
            name='tanda_tangan_digital',
        ),
    ]
